# Generated by Django 4.0.4 on 2022-04-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('css_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='css_app.post'),
        ),
    ]
